name: tests
on: [workflow_dispatch]
jobs:
  tests:
    name: node ${{ matrix.node-version }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [16, 14, 12]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: dmitry-shibanov/setup-node@v-dmshib/add-cache-dependencies-path
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm i -g yarn@1
      - run: yarn config set network-timeout 300000
      - run: yarn --frozen-lockfile
      - run: yarn test
