name: tests
on: [workflow_dispatch]
jobs:
  tests:
    name: node ${{ matrix.node-version }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        node-version: [16, 14, 12]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: dmitry-shibanov/setup-node@v-dmshib/add-cache-dependencies-path
        with:
          node-version: ${{ matrix.node-version }}

      - name: components
        run: npm install
        working-directory: packages/components
        
      - name: app
        run: npm install
        working-directory: packages/app
        
      - name: server
        run: npm install
        working-directory: packages/server
